### ISSUE TITLE
[Question] How to specify a 'user' when using postgres socket syntax?

### ISSUE THREAD

**Issue by elbenfreund** [kennethreitz/dj-database-url#103]
As per `README` it is possible to specify a postgres db via a *socket url*. What is not clear to me from the example is, how to include the 'user' parameter in this specific syntax.
Any pointers would be most appreciated.

**Comment by sigmavirus24** [comment]
This is a little light on details, but I think I know what you're trying to ask. If I miss the point, please let me know and maybe provide more details.

So, in our README, we describe the [URL Schema](https://github.com/kennethreitz/dj-database-url#url-schema) where `postgres://USER:PASSWORD@HOST:PORT/NAME` is described as acceptable. It also has a link to [this footnote](https://github.com/kennethreitz/dj-database-url#id5) which describes the socket variant of `postgres://%2Fvar%2Flib%2Fpostgresql/dbname`. In this case we would parse the socket variant with `%2Fvar%2Flib%2Fpostgresql` as the `HOST` portion in the example above. That means that `postgres://USER@%2Fvar%2Flib%2Fpostgresql/dbname` should be valid. If you also need to specify the password then `postgres://USER:PASSWORD@%2Fvar%2Flib%2Fpostgresql/dbname` should be valid as well.

Please close this if that answers your question

**Comment by elbenfreund** [comment]
Thanks a lot! :+1:
