### ISSUE TITLE
Add support for mongodb

### ISSUE THREAD

**Issue by arruda** [kennethreitz/dj-database-url#46]
I'm not sure if there is a impediment for this, but if not, it would be a nice feature to have.

Here is an example (not sure if it's a good one thou):
https://github.com/RyanBalfanz/django-mongo-database-url

**Comment by arruda** [comment]
Forget about it... just know I saw that django don't work well with mongo... and there is a REwrite on django source to do that...
sorry for the issue here =/

**Comment by ZuluPro** [comment]
@kennethreitz : And what if I really would like to have a MongoDB engine ?
What should I do, a PR ?

**Comment by Vichoko** [comment]
+1 for Djongo engine (MongoDB)
