### ISSUE TITLE
MySQL backend doesn't work on python 3

### ISSUE THREAD

**Issue by igorcamp** [kennethreitz/dj-database-url#53]
'django.db.backends.mysql' uses MySQL-python lib, but this lib does not support python 3.

You could use another backend when python 3 is used. The mysql-connector-python lib already comes with a django backend: 'mysql.connector.django'. It is a good alternative.

**Comment by kennethreitz** [comment]
The `django.db.backends.mysql` backend now automatically uses `mysqlclient`, which supports both Python 2 and 3.

https://github.com/django/django/blob/master/django/db/backends/mysql/base.py#L4
