### ISSUE TITLE
Document the 'env' parameter

### ISSUE THREAD

**Issue by edmorley** [kennethreitz/dj-database-url#54]
dj-database-url defaults to reading in the value of DATABASE_URL, but this can be overridden using `env`, like so:
```python
DATABASES = {
    'default': dj_database_url.config(),
    'read_only': dj_database_url.config(env='DATABASE_URL_RO')
}
```
It would be good to mention this in the README.
I'll open a PR when I get a chance soon, if someone hasn't beaten me to it :-)

**Comment by kennethreitz** [comment]
Will consider it :)
