### ISSUE TITLE
Doc site is down

### ISSUE THREAD

**Issue by qrilka** [kennethreitz/dj-database-url#56]
https://crate.io/packages/dj-database-url/ returns 502

**Comment by ShamsGolap** [comment]
Up! Returns 404 now

**Comment by TonyPythoneer** [comment]
I get the return is `410 Gone`!!

**Comment by kennethreitz** [comment]
Fixed the URL. Thanks!

**Comment by ShamsGolap** [comment]
`410 Gone` is back :'(

**Comment by kennethreitz** [comment]
@shamsgolap the URL is not the one specified above

**Comment by ShamsGolap** [comment]
Oh ok, thanks !
