### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by johntellsall** [kennethreitz/dj-database-url#68]
I'd like to tell Django what my Redis cache (database) is via a URL.

We can borrow the format from https://github.com/ddollar/redis-url#url-format :

`redis://[:password@]host[:port][/db-number][?option=value]`

**Comment by f0r4y312** [comment]
@johntellsall https://github.com/f0r4y312/django-connection-url. shameless self-plug alert, but I am currently using it for redis, memcached and local memory cache config

**Comment by f0r4y312** [comment]
@johntellsall after reading @jdp's comment in your pull request #69, i'll be trying out [django-cache-url](https://github.com/ghickman/django-cache-url).

**Comment by kennethreitz** [comment]
Merged!
