### ISSUE TITLE
cxOracle(and Django) expects port numbers as strings not integers

### ISSUE THREAD

**Issue by GertBurger** [kennethreitz/dj-database-url#85]
With a port number specified in the url cxOracle fails as follows:
> File "/home/test/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 213, in get_new_connection
>     conn_string = convert_unicode(self._connect_string())
>   File "/home/test/.virtualenvs/test/local/lib/python2.7/site-packages/django/db/backends/oracle/base.py", line 197, in _connect_string
>     if settings_dict['PORT'].strip():
> AttributeError: 'int' object has no attribute 'strip'

I had a look at the Django docs and it shows database ports as strings.

**Comment by kennethreitz** [comment]
PRs accepted!
