### ISSUE TITLE
Want to set `False` value in options.

### ISSUE THREAD

**Issue by pistatium** [kennethreitz/dj-database-url#87]
I want to pass a value of `False` to Django.
For example, `?use_unicode=False`.

```py
DATABASES['default']['OPTIONS']['use_unicode'] = 'False'  #=> True
```

However, if you do this, it will be set as a character string as above.

Even if `?use_unicode=0`, `'0'` is treated as True in Python, so it does not become the expected value.

Is there a way to set False appropriately?

**Comment by kennethreitz** [comment]
The best practice is to update this value manually after invoking dj-database-url.
