### ISSUE TITLE
Database URL not updating database connection even when URL in settings is changed

### ISSUE THREAD

**Issue by JadSayegh** [kennethreitz/dj-database-url#94]
When trying to switch URLs on the same host e.g. `postgresql://user:secret@localhost/my_db_1` to `postgresql://user:secret@localhost/my_db_2`, Django wasn't reflecting the change when I did this and kept connecting to `my_db_1`
```
$ python manage.py shell

>> from django import db
>> db.connection.settings_dict['NAME']
"my_db_1"

```
I changed back to using the normal Django database settings dict (instead of a URL with dj-database-url) and it worked. What could be causing this?

**Comment by sigmavirus24** [comment]
We'd need significantly more detail before we'd be able to help you. Including, but not limited to:

- What your settings.py looks like
- What versions of django, dj-database-url, and python you're using

**Comment by JadSayegh** [comment]
Hi Sigma, this was so long ago.. I would have to try to recreate the issue.

**Comment by sigmavirus24** [comment]
It sounds like you're no longer encountering this. With that in mind, I'm going to close this until we know more.
