### ISSUE TITLE
Django 2.0: django.db.backends.postgresql_psycopg2 module is deprecated

### ISSUE THREAD

**Issue by lwm** [kennethreitz/dj-database-url#96]
https://docs.djangoproject.com/en/2.0/releases/2.0/#id1

> The django.db.backends.postgresql_psycopg2 module is deprecated in favor of django.db.backends.postgresql. It’s been an alias since Django 1.9. This only affects code that imports from the module directly. The DATABASES setting can still use 'django.db.backends.postgresql_psycopg2', though you can simplify that by using the 'django.db.backends.postgresql' name added in Django 1.9.

Not something that will break code now but something to keep in mind. Just dropping that here.

https://github.com/kennethreitz/dj-database-url/blob/master/dj_database_url.py#L31

**Comment by kennethreitz** [comment]
:+1:
