### ISSUE TITLE
Support for multiple databases through env variables

### ISSUE THREAD

**Issue by r3r00t3d** [kennethreitz/dj-database-url#99]
Hi,

just wanted to ask what is the easiest way to interact with multiple databases via env variables? I would like to use DATABASE_URL but I cannot see an easy way to do this.

Thanks.

**Comment by r4vi** [comment]
hi @r3r00t3d by default it reads from `DATABASE_URL` if you would like to read from _another_ variable just import it:
```python
import os, dj_database_url

DATABASES['default'] = dj_database_url.parse(os.environ['SOME_OTHER_VARIABLE', conn_max_age=600)
```

**Comment by r3r00t3d** [comment]
Thank you. I appreciate the answer.
